# Generated by Django 3.0.5 on 2021-02-12 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='alias',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 12, 17, 28, 2, 247793, tzinfo=utc)),
        ),
    ]
