# Generated by Django 3.0.5 on 2021-02-12 17:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0002_auto_20210212_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='end',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='alias',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 12, 17, 29, 29, 830306, tzinfo=utc)),
        ),
    ]
